import XLSX from "xlsx";
import ExcelJS from "exceljs";
import { DEFAULT_CLASSIFICATION_RULES, DEFAULT_FACILITIES, DEFAULT_PACKAGE_COMPONENTS } from "../src/components/nicepayVatDefaults.ts";
import { buildVatSettlementWorkbook, REFERENCE_HIDDEN_REPORT_COLUMNS } from "../src/components/nicepayVatWorkbook.ts";
import { isNicepayTargetMid, processVatSettlement, type RawRow } from "../src/components/nicepayVatEngine.ts";

const sourcePath = process.argv[2];
if (!sourcePath) throw new Error("사용법: node --experimental-strip-types scripts/verify-nicepay-vat-sample.ts <raw-data.xls>");
const workbook = XLSX.readFile(sourcePath, { cellDates: false, raw: true });
const sheet = workbook.Sheets[workbook.SheetNames[0]];
const matrix = XLSX.utils.sheet_to_json<unknown[]>(sheet, { header: 1, defval: "", raw: true });
const headers = matrix[0].map((value, index) => String(value || `열${index + 1}`));
const allRows: RawRow[] = matrix.slice(1).filter((row) => row.some((value) => value !== "" && value !== null)).map((row, index) => Object.fromEntries([...headers.map((header, column) => [header, row[column] ?? ""]), ["__sourceRowNumber", index + 2]]));
const rows = allRows.filter((row) => isNicepayTargetMid(row.MID));
const result = processVatSettlement(rows, DEFAULT_CLASSIFICATION_RULES, DEFAULT_PACKAGE_COMPONENTS, DEFAULT_FACILITIES);
if (result.report.inputCount !== rows.length) throw new Error("입력 행 수와 처리 행 수가 다릅니다.");
if (result.summaries.some((summary) => summary.validation === "정상" && summary.difference !== 0)) throw new Error("정상 배분 항목의 차이가 0원이 아닙니다.");
const output = new ExcelJS.Workbook();
buildVatSettlementWorkbook(output, rows, result, DEFAULT_CLASSIFICATION_RULES, DEFAULT_PACKAGE_COMPONENTS, DEFAULT_FACILITIES, true);
const buffer = await output.xlsx.writeBuffer();
if (!output.worksheets.some((sheet) => sheet.name === "2607월 부가세") || buffer.byteLength < 1000) throw new Error("보고서 Excel 생성 검증에 실패했습니다.");
const report = output.getWorksheet("2607월 부가세");
if (!report || REFERENCE_HIDDEN_REPORT_COLUMNS.some((column) => !report.getColumn(column).hidden)) throw new Error("기준 보고서 숨김 열 복제 검증에 실패했습니다.");
const allocationHeaderRow = result.rows.length + 9;
const allocationTotalRow = allocationHeaderRow + result.summaries.length + 1;
if (report.getCell(allocationTotalRow, 30).value !== "합계") throw new Error("업장별 배분표의 세로 합계 행이 없습니다.");
const totalFormula = report.getCell(allocationTotalRow, 63).value as { formula?: string; result?: number };
const differenceFormula = report.getCell(allocationTotalRow, 66).value as { formula?: string; result?: number };
if (!totalFormula.formula?.startsWith("SUM(BK") || totalFormula.result !== result.report.feeAfterAllocation) throw new Error("업장별 배분 합계 검증 수식이 올바르지 않습니다.");
if (differenceFormula.formula !== `BK${allocationTotalRow}-BL${allocationTotalRow}` || result.report.feeAfterAllocation - result.report.feeBeforeAllocation !== 0) throw new Error("최종 배분 차이 검증 수식이 올바르지 않습니다.");
DEFAULT_FACILITIES.filter((facility) => facility.enabled).forEach((facility) => {
  const expected = result.report.facilityTotals[facility.name] || 0;
  const cell = report.getCell(`${facility.excelColumn}${allocationTotalRow}`).value as { formula?: string; result?: number };
  if (!cell.formula?.startsWith(`SUM(${facility.excelColumn}`) || (expected !== 0 && cell.result !== expected)) throw new Error(`업장별 합계가 맞지 않습니다: ${facility.name}`);
});
console.log(JSON.stringify({ sourceRows: allRows.length, midExcluded: allRows.length - rows.length, inputRows: rows.length, processedRows: result.report.outputCount, classified: result.report.classifiedCount, unclassified: result.report.unclassifiedCount, allocationRows: result.summaries.length, feeBefore: result.report.feeBeforeAllocation, feeAfter: result.report.feeAfterAllocation, allocationDifferences: result.report.allocationDifferenceCount, outputSheets: output.worksheets.length, outputBytes: buffer.byteLength }, null, 2));
